name: API and Web Automation

on:
  workflow_dispatch:     # Bisa trigger manual dari tab Actions GitHub
  pull_request:
    branches:
      - main           # Otomatis jalan setiap ada PR ke main

permissions:
  contents: write        # Izin untuk read/write content repo
  pages: write           # Izin untuk deploy ke GitHub Pages
  id-token: write        # Izin untuk OIDC token (required oleh Pages action)

jobs:
  api-tests:
    name: Run API Tests (@api)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run API tests
        run: ./gradlew clean test -Dcucumber.filter.tags="@api" --stacktrace --info

      - name: Archive API test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Test Reports
          path: build/reports/tests/test

      - name: Deploy API test reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/tests/test
          publish_branch: gh-pages
          destination_dir: api-reports

  web-tests:
    name: Run Web Tests (@web)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: stable

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run Web tests
        run: xvfb-run ./gradlew clean test -Dcucumber.filter.tags="@web" --stacktrace --info

      - name: Archive Web test reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Web Test Reports
          path: build/reports/tests/test

      - name: Deploy Web test reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/tests/test
          publish_branch: gh-pages
          destination_dir: web-reports
