name: API and Web Automation

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  api-tests:
    name: Run API Tests (@api)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run API Tests
        run: ./gradlew clean apiTest --stacktrace --info

      - name: Upload API Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: API Test Reports
          path: build/reports/api-cucumber-html-report

      - name: Deploy API Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/api-cucumber-html-report
          publish_branch: gh-pages
          destination_dir: api-reports

  web-tests:
    name: Run Web Tests (@web)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@v1.7.3
        with:
          chrome-version: stable

      - name: Symlink chrome if needed
        run: |
          if [ ! -f /usr/bin/google-chrome ]; then
            sudo ln -s /usr/bin/google-chrome-stable /usr/bin/google-chrome
          fi

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper/
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle.lockfile') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Build project
        run: ./gradlew build

      - name: Run Web Tests
        run: xvfb-run ./gradlew clean webTest --stacktrace --info

      - name: Upload Web Test Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: Web Test Reports
          path: build/reports/web-cucumber-html-report

      - name: Deploy Web Reports to GitHub Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/reports/web-cucumber-html-report
          publish_branch: gh-pages
          destination_dir: web-reports
